Algoritmo "EXERCÍCIO 24"
Var
REAIS, DOLAR, MARCO, LIBRAE : REAL
Inicio
Escreval ("Eu converto o real em diversas moedas")
Escreval ("Quantos reais você gostaria de converter?")
Leia (reais)
dolar <- reais /1.8
marco <- reais / 2
librae <- reais / 3.57
Escreval (" Com essa quantia, você possuí: ", dolar, " DE DOLARES, ", MARCO, " DE MARCO ALEMÃO, ", librae, " DE LIBRA ESTERLINA.")
 
 
Fimalgoritmo