Algoritmo "Exercício 6"
//  
//  

Var
salb, salr, valorv, comissao : real
Inicio
Escreval ("Gostaria de saber quanto receberá este mês?")
Escreval ("Vamos lá, me informe qual o seu salário base")
Leia (salb)
Escreval ("Me informe qual valor total de suas vendas")
leia (valorv)
comissao <- valorv * 0.04
salr <- salb + comissao
escreval ("O seu Salário será de R$:" , salr, " neste mês, sendo R$", comissao ," de comissão")

Fimalgoritmo